### ISSUE TITLE
PYPI Chartbeat

### ISSUE THREAD

**Issue by neurosnap** [cyberdelia/chartbeat#3]
I cannot seem to find this python package in pypi, is there any reason for this?

I'm also noticing a couple tests are failing as well

line 24:
    def test_quickstats():
        data = self.beat.quickstats(path="/")

data returns empty {}

**Comment by cyberdelia** [comment]
I was pretty sure I pushed it, I see you've done it too since :|

**Comment by neurosnap** [comment]
Hey Timothee, if you want me to take it down, I'll respect your wishes. I
did it because of a project I was working on, you are more than welcome to
publish your version.

On Tue, Jun 24, 2014 at 1:37 PM, Timothée Peignier <notifications@github.com

**Comment by cyberdelia** [comment]
@neurosnap I would rather give you access to this repo as you are maintaining and using it, as you prefer.
